//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Es.Udc.DotNet.PracticaMaD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recommendation
    {
        public long recomId { get; set; }
        public string justification { get; set; }
        public System.DateTime recommendationDate { get; set; }
        public long eventId { get; set; }
        public long groupId { get; set; }
        public long userId { get; set; }
    
        public virtual EventTable EventTable { get; set; }
        public virtual GroupTable GroupTable { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
